/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 7.0.12 */
package parser;

public interface MyParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTMT = 1;
  public int JJTEXPR1 = 2;
  public int JJTNUMBER = 3;
  public int JJTADDOPERATOR = 4;


  public String[] jjtNodeName = {
    "program",
    "stmt",
    "expr1",
    "Number",
    "AddOperator",
  };
}
/* JavaCC - OriginalChecksum=2bb4c66efb4fcddcb0158aa6372ee821 (do not edit this line) */
